# Generated by Django 4.0.1 on 2022-01-30 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Ingredient's name")),
                ('measurement_unit', models.CharField(max_length=50, verbose_name="Ingredient's measurement unit")),
            ],
        ),
        migrations.CreateModel(
            name='IngredientForRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, "Amount can't be less than 1")], verbose_name="Ingredient's amount")),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Recipe's name")),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name="Recipe's image")),
                ('text', models.TextField(verbose_name="Recipe's text")),
                ('cooking_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, "Time of cooking can't be less then 1 minute.")], verbose_name='Cooking time in minutes')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Tag's name")),
                ('color', models.CharField(max_length=7, verbose_name="Tag's color")),
                ('slug', models.SlugField(unique=True, verbose_name="Tag's slug")),
            ],
        ),
    ]
